export const themeConfig = {
  // ── Original structural themes ─────────────────────────────────────────────
  light: {
    "--bg-main":        "#F5F4F1",
    "--bg-card":        "#FFFFFF",
    "--bg-soft":        "#EEECEA",
    "--text-primary":   "#0A1A0F",
    "--text-secondary": "#4A6555",
    "--text-muted":     "#9AAFA3",
    "--text-inverse":   "#0A1A0F",
    "--border-color":   "#E2E0DC",
  },
  dark: {
    "--bg-main":        "#0F172A",
    "--bg-card":        "#1E293B",
    "--bg-soft":        "#334155",
    "--text-primary":   "#E2E8F0",
    "--text-secondary": "#94A3B8",
    "--text-muted":     "#64748B",
    "--text-inverse":   "#FFFFFF",
    "--border-color":   "#334155",
  },
  night: {
    "--bg-main":        "#020617",
    "--bg-card":        "#0F172A",
    "--bg-soft":        "#1E293B",
    "--text-primary":   "#CBD5F5",
    "--text-secondary": "#64748B",
    "--text-muted":     "#475569",
    "--text-inverse":   "#FFFFFF",
    "--border-color":   "#1E293B",
  },

  // ── Pastel Brand Palettes ──────────────────────────────────────────────────
  // Each palette defines background, card, soft, text + brand accent variables

  "sage": {
    "--bg-main":        "#F0F5F1",
    "--bg-card":        "#FFFFFF",
    "--bg-soft":        "#E4EDE6",
    "--text-primary":   "#0A1F12",
    "--text-secondary": "#4B6B57",
    "--text-muted":     "#8BA898",
    "--text-inverse":   "#0A1F12",
    "--border-color":   "#D6E4DA",
    "--brand-primary":  "#3DAA3A",
    "--brand-accent":   "#6EDC5F",
    "--brand-highlight":"#A8F5A2",
  },

  "lavender": {
    "--bg-main":        "#F5F0FF",
    "--bg-card":        "#FFFFFF",
    "--bg-soft":        "#EBE4FF",
    "--text-primary":   "#1A0A3F",
    "--text-secondary": "#5B4B80",
    "--text-muted":     "#9D8BC0",
    "--text-inverse":   "#1A0A3F",
    "--border-color":   "#DDD5F5",
    "--brand-primary":  "#7B3FE4",
    "--brand-accent":   "#A78BFA",
    "--brand-highlight":"#C4B5FD",
  },

  "sky": {
    "--bg-main":        "#F0F7FF",
    "--bg-card":        "#FFFFFF",
    "--bg-soft":        "#E0EFFF",
    "--text-primary":   "#0A1F3F",
    "--text-secondary": "#3B5A7F",
    "--text-muted":     "#7EA8CC",
    "--text-inverse":   "#0A1F3F",
    "--border-color":   "#C8DEFF",
    "--brand-primary":  "#2563EB",
    "--brand-accent":   "#60A5FA",
    "--brand-highlight":"#BAE6FD",
  },

  "rose": {
    "--bg-main":        "#FFF5F7",
    "--bg-card":        "#FFFFFF",
    "--bg-soft":        "#FFE8EC",
    "--text-primary":   "#3F0A1A",
    "--text-secondary": "#804055",
    "--text-muted":     "#CC8898",
    "--text-inverse":   "#3F0A1A",
    "--border-color":   "#F5D0D8",
    "--brand-primary":  "#E11D48",
    "--brand-accent":   "#FB7185",
    "--brand-highlight":"#FCA5A5",
  },

  "amber": {
    "--bg-main":        "#FFFBF0",
    "--bg-card":        "#FFFFFF",
    "--bg-soft":        "#FFF3D6",
    "--text-primary":   "#2D1A00",
    "--text-secondary": "#7A5200",
    "--text-muted":     "#C49A3A",
    "--text-inverse":   "#2D1A00",
    "--border-color":   "#F0E0B0",
    "--brand-primary":  "#D97706",
    "--brand-accent":   "#FCD34D",
    "--brand-highlight":"#FDE68A",
  },
};

// ── Palette metadata for the UI picker ─────────────────────────────────────
export const PALETTE_META = [
  {
    id:      "sage",
    label:   "Sage Green",
    emoji:   "🌿",
    swatch:  "#3DAA3A",
    bg:      "#F0F5F1",
    desc:    "Fresh, natural — the default UpGrAIEd look",
  },
  {
    id:      "lavender",
    label:   "Lavender",
    emoji:   "💜",
    swatch:  "#7B3FE4",
    bg:      "#F5F0FF",
    desc:    "Calm and creative — great for learning focus",
  },
  {
    id:      "sky",
    label:   "Sky Blue",
    emoji:   "☁️",
    swatch:  "#2563EB",
    bg:      "#F0F7FF",
    desc:    "Clear and trustworthy — clean and airy",
  },
  {
    id:      "rose",
    label:   "Rose",
    emoji:   "🌸",
    swatch:  "#E11D48",
    bg:      "#FFF5F7",
    desc:    "Warm and energetic — vibrant and bold",
  },
  {
    id:      "amber",
    label:   "Amber",
    emoji:   "🌻",
    swatch:  "#D97706",
    bg:      "#FFFBF0",
    desc:    "Sunny and warm — optimistic and friendly",
  },
];
